// Code generated by mockery v2.42.0. DO NOT EDIT.

package dbmocks

import (
	context "context"

	db "github.com/github-real-lb/bookings-web-app/db"
	mock "github.com/stretchr/testify/mock"
)

// MockDBStore is an autogenerated mock type for the DatabaseStore type
type MockDBStore struct {
	mock.Mock
}

// CheckRoomAvailability provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CheckRoomAvailability(ctx context.Context, arg db.CheckRoomAvailabilityParams) (bool, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CheckRoomAvailability")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CheckRoomAvailabilityParams) (bool, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CheckRoomAvailabilityParams) bool); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CheckRoomAvailabilityParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateReservation provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CreateReservation(ctx context.Context, arg db.CreateReservationParams) (db.Reservation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) (db.Reservation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) db.Reservation); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateReservationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateReservationTx provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CreateReservationTx(ctx context.Context, arg db.CreateReservationParams) (db.Reservation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservationTx")
	}

	var r0 db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) (db.Reservation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateReservationParams) db.Reservation); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateReservationParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoom provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CreateRoom(ctx context.Context, arg db.CreateRoomParams) (db.Room, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) (db.Room, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomParams) db.Room); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoomRestriction provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CreateRoomRestriction(ctx context.Context, arg db.CreateRoomRestrictionParams) (db.RoomRestriction, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoomRestriction")
	}

	var r0 db.RoomRestriction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomRestrictionParams) (db.RoomRestriction, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateRoomRestrictionParams) db.RoomRestriction); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.RoomRestriction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateRoomRestrictionParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAllReservations provides a mock function with given fields: ctx
func (_m *MockDBStore) DeleteAllReservations(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllReservations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllRoomRestrictions provides a mock function with given fields: ctx
func (_m *MockDBStore) DeleteAllRoomRestrictions(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllRoomRestrictions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllRooms provides a mock function with given fields: ctx
func (_m *MockDBStore) DeleteAllRooms(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteReservation provides a mock function with given fields: ctx, id
func (_m *MockDBStore) DeleteReservation(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoom provides a mock function with given fields: ctx, id
func (_m *MockDBStore) DeleteRoom(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoomRestriction provides a mock function with given fields: ctx, id
func (_m *MockDBStore) DeleteRoomRestriction(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoomRestriction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockDBStore) DeleteUser(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastRoomRestriction provides a mock function with given fields: ctx, roomID
func (_m *MockDBStore) GetLastRoomRestriction(ctx context.Context, roomID int64) (db.RoomRestriction, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRoomRestriction")
	}

	var r0 db.RoomRestriction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.RoomRestriction, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.RoomRestriction); ok {
		r0 = rf(ctx, roomID)
	} else {
		r0 = ret.Get(0).(db.RoomRestriction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReservation provides a mock function with given fields: ctx, id
func (_m *MockDBStore) GetReservation(ctx context.Context, id int64) (db.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReservationByCode provides a mock function with given fields: ctx, code
func (_m *MockDBStore) GetReservationByCode(ctx context.Context, code string) (db.Reservation, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByCode")
	}

	var r0 db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Reservation, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Reservation); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReservationByLastName provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) GetReservationByLastName(ctx context.Context, arg db.GetReservationByLastNameParams) (db.Reservation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationByLastName")
	}

	var r0 db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetReservationByLastNameParams) (db.Reservation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetReservationByLastNameParams) db.Reservation); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Reservation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetReservationByLastNameParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoom provides a mock function with given fields: ctx, id
func (_m *MockDBStore) GetRoom(ctx context.Context, id int64) (db.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.Room); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Room)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoomRestriction provides a mock function with given fields: ctx, id
func (_m *MockDBStore) GetRoomRestriction(ctx context.Context, id int64) (db.RoomRestriction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomRestriction")
	}

	var r0 db.RoomRestriction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.RoomRestriction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.RoomRestriction); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.RoomRestriction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockDBStore) GetUser(ctx context.Context, id int64) (db.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (db.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) db.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAvailableRooms provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListAvailableRooms(ctx context.Context, arg db.ListAvailableRoomsParams) ([]db.Room, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableRooms")
	}

	var r0 []db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAvailableRoomsParams) ([]db.Room, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListAvailableRoomsParams) []db.Room); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListAvailableRoomsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReservations provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListReservations(ctx context.Context, arg db.ListReservationsParams) ([]db.Reservation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListReservations")
	}

	var r0 []db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListReservationsParams) ([]db.Reservation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListReservationsParams) []db.Reservation); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListReservationsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListReservationsByRoom provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListReservationsByRoom(ctx context.Context, arg db.ListReservationsByRoomParams) ([]db.Reservation, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListReservationsByRoom")
	}

	var r0 []db.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListReservationsByRoomParams) ([]db.Reservation, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListReservationsByRoomParams) []db.Reservation); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListReservationsByRoomParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRoomRestrictions provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListRoomRestrictions(ctx context.Context, arg db.ListRoomRestrictionsParams) ([]db.RoomRestriction, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRoomRestrictions")
	}

	var r0 []db.RoomRestriction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRoomRestrictionsParams) ([]db.RoomRestriction, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRoomRestrictionsParams) []db.RoomRestriction); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.RoomRestriction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListRoomRestrictionsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRooms provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListRooms(ctx context.Context, arg db.ListRoomsParams) ([]db.Room, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRooms")
	}

	var r0 []db.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRoomsParams) ([]db.Room, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListRoomsParams) []db.Room); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListRoomsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []db.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) ([]db.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.ListUsersParams) []db.User); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.ListUsersParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReservation provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) UpdateReservation(ctx context.Context, arg db.UpdateReservationParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateReservationParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoom provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) UpdateRoom(ctx context.Context, arg db.UpdateRoomParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRoomRestriction provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) UpdateRoomRestriction(ctx context.Context, arg db.UpdateRoomRestrictionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoomRestriction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateRoomRestrictionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockDBStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateUserParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockDBStore creates a new instance of MockDBStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBStore {
	mock := &MockDBStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
